# Dubbo ???
dubbo:
  application:
    name: dubbo-producer
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
  # ???? WEB ????
server:
  port: 9090

